# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9cceca962599208a7651f992932b11206c579f1fc8702a054e9679084cc1ddf7fcae718b3689a1e310e91a827a794b448af86362a2320ce2e26445c7f1edea4

test:
  secret_key_base: 832783d986da0f8e5bbe35bb0916cb23c88eee50f25b1463990e817052c8db5602dc192ccf4052f816f15c8b1b8b74bb6fb825f546754d4c468e21060ad71b39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
